from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 636)
        MainWindow.setFixedSize(800, 645)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.n_label = QtWidgets.QLabel(self.centralwidget)
        self.n_label.setGeometry(QtCore.QRect(10, 50, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.n_label.setFont(font)
        self.n_label.setObjectName("n_label")
        self.n_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.n_lineEdit.setGeometry(QtCore.QRect(250, 60, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.n_lineEdit.setFont(font)
        self.n_lineEdit.setObjectName("n_lineEdit")
        self.m_label = QtWidgets.QLabel(self.centralwidget)
        self.m_label.setGeometry(QtCore.QRect(10, 100, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.m_label.setFont(font)
        self.m_label.setObjectName("m_label")
        self.m_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.m_lineEdit.setGeometry(QtCore.QRect(250, 110, 113, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.m_lineEdit.setFont(font)
        self.m_lineEdit.setObjectName("m_lineEdit")
        self.alpha_label = QtWidgets.QLabel(self.centralwidget)
        self.alpha_label.setGeometry(QtCore.QRect(10, 150, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.alpha_label.setFont(font)
        self.alpha_label.setObjectName("alpha_label")
        self.alpha_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.alpha_doubleSpinBox.setGeometry(QtCore.QRect(250, 160, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.alpha_doubleSpinBox.setFont(font)
        self.alpha_doubleSpinBox.setMaximum(1.0)
        self.alpha_doubleSpinBox.setSingleStep(0.1)
        self.alpha_doubleSpinBox.setObjectName("alpha_doubleSpinBox")
        self.exp_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.exp_pushButton.setGeometry(QtCore.QRect(80, 530, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exp_pushButton.setFont(font)
        self.exp_pushButton.setObjectName("exp_pushButton")
        self.gr2_label = QtWidgets.QLabel(self.centralwidget)
        self.gr2_label.setGeometry(QtCore.QRect(530, 310, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gr2_label.setFont(font)
        self.gr2_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gr2_label.setObjectName("gr2_label")
        self.graph1_widget = PlotWidget(self.centralwidget)
        self.graph1_widget.setGeometry(QtCore.QRect(380, 40, 411, 261))
        self.graph1_widget.setObjectName("graph1_widget")
        self.graph2_widget = PlotWidget(self.centralwidget)
        self.graph2_widget.setGeometry(QtCore.QRect(380, 350, 411, 231))
        self.graph2_widget.setObjectName("graph2_widget")
        self.gr1_label = QtWidgets.QLabel(self.centralwidget)
        self.gr1_label.setGeometry(QtCore.QRect(440, 0, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.gr1_label.setFont(font)
        self.gr1_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.gr1_label.setObjectName("gr1_label")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(10, 470, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.result_label.setFont(font)
        self.result_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result_label.setObjectName("result_label")
        self.resultLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.resultLineEdit.setGeometry(QtCore.QRect(100, 470, 261, 31))
        self.resultLineEdit.setMinimumSize(QtCore.QSize(171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resultLineEdit.setFont(font)
        self.resultLineEdit.setInputMask("")
        self.resultLineEdit.setText("")
        self.resultLineEdit.setReadOnly(True)
        self.resultLineEdit.setObjectName("resultLineEdit")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(360, 0, 16, 581))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 510, 351, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 440, 351, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 30, 351, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        self.info_label.setGeometry(QtCore.QRect(130, 0, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info_label.setFont(font)
        self.info_label.setObjectName("info_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лабораторная работа №1"))
        self.n_label.setText(_translate("MainWindow", "Количество экспериментов:"))
        self.n_lineEdit.setInputMask(_translate("MainWindow", "#00000"))
        self.n_lineEdit.setText(_translate("MainWindow", "1000"))
        self.m_label.setText(_translate("MainWindow", "Количество серий:"))
        self.m_lineEdit.setInputMask(_translate("MainWindow", "#00000"))
        self.m_lineEdit.setText(_translate("MainWindow", "100"))
        self.alpha_label.setText(_translate("MainWindow", "Коэффициент доверия:"))
        self.exp_pushButton.setText(_translate("MainWindow", "Провести эксперимент"))
        self.gr2_label.setText(_translate("MainWindow", "График ошибки"))
        self.gr1_label.setText(_translate("MainWindow", "График зависимости частоты от N"))
        self.result_label.setText(_translate("MainWindow", "Результат:"))
        self.info_label.setText(_translate("MainWindow", "Ввод данных"))
